<?php

/**
 * Implements hook_help().
 */
function ckstyle_help($path, $arg) {
  if ($path == 'admin/help#ckstyle') {
    return t('Adds styles that can be used by the CKEditor.');
  }
}

/**
 * Implements hook_wysiwyg_editor_settings_alter
 */
function ckstyle_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == "ckeditor") {
    $settings['customConfig'] = base_path() . drupal_get_path('module', 'ckstyle') . '/ckstyle.js';
  }
}
